### ISSUE TITLE
In Dreams

### ISSUE THREAD

**Issue by Jahone** [WoWFeenix/Warsong-Realm#80] opened 2018-05-30 08:09 UTC
Completed the quest In Dreams but Tirion Fordring wont give me any rewards.
Tried relog was not in a raidgroup and some others had same issues.
Please fix so i can turn in my Quest

**Comment by WoWFeenix** [comment] 2018-06-05 02:58
Duplicate of #60

**Closed by WoWFeenix** 2018-06-05 02:58 UTC
Labels: duplicate
