### ISSUE TITLE
Can't talk / interract with Donova Snowden

### ISSUE THREAD

**Issue by Gillian8** [WoWFeenix/Warsong-Realm#35] opened 2018-05-22 21:18 UTC
Hello
The NPC Donova Snowden in Winterspring isn't working, can't talk to her or hand in quests
There was another player with me and it was the same for him

Thank you :)

**Comment by warlorddrak** [comment] 2018-05-29 10:36
Duplicate of #19

**Comment by WoWFeenix** [comment] 2018-06-05 01:18
Duplicate of #19

**Closed by WoWFeenix** 2018-06-05 01:18 UTC
Labels: duplicate
