### ISSUE TITLE
NPC Donova Snowden

### ISSUE THREAD

**Issue by shadowbola** [WoWFeenix/Warsong-Realm#68] opened 2018-05-28 16:53 UTC
**When it occured: ** 05/28/2018 6:49 PM

**Description: ** I have some quests to finish on this NPC, but it doesnt show. 

**How it works: ** Dont work

**How it should work: ** I could finish the quest on this NPC

**Link to WoWHead/WoWWiki: ** 
http://wowwiki.wikia.com/wiki/Quest:Mystery_Goo
http://wowwiki.wikia.com/wiki/Donova_Snowden

**Comment by warlorddrak** [comment] 2018-05-29 10:36
Duplicate of #19

**Comment by WoWFeenix** [comment] 2018-06-05 01:18
Duplicate of #19

**Closed by WoWFeenix** 2018-06-05 01:18 UTC
Labels: duplicate
